language: node_js

node_js: stable

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "hipye"
  - git config user.email "morizen@163.com"
  - git add .
  - git commit -m "Deploy blog pages"
  - git push --force --quiet "https://${gh_token}@github.com/hipye/hipye.github.io" master:master

branches:
  only:
    - hexo
