alias ai "apt install -y"
alias aa "aria2c -x 16"
alias ug "apt update && apt upgrade -y"
alias gitconfig "git config --global user.email "i@omoe.cc" && git config --global user.name "hipye""
alias cdd "cd /data/data/com.termux/files"
alias zzz "ssh moriz@192.168.8.171"
alias xxx "ssh root@192.168.8.234"
alias ccc "ssh root@192.168.8.1"
