alias sai "sudo apt install -y"
alias sug "sudo apt update && sudo apt upgrade -y"
alias sar "sudo apt remove -y"
alias sas "sudo apt search"
alias ar "apt remove -y"
alias as "apt search"
alias ai "apt install -y"
alias ug "apt update && apt upgrade -y"

alias cdd "cd /data/data/com.termux/files"
alias zzz "ssh moriz@192.168.8.171"
alias xxx "ssh root@192.168.8.234"
alias ccc "ssh root@192.168.8.1"

alias gpp "git add . && git commit -m "update" && git push"
alias gitconfig "git config --global user.email "i@omoe.cc" && git config --global user.name "hipye" && git config --global pull.rebase true && git config --global branch.autoSetupRebase always"
alias gc "git clone"

alias aa "aria2c -x 16"
alias cpfish "cp st/config.fish ~/.config/fish/ && fish"
